- name: install windows adk
  win_package:
    path: "{{ win_adk_download_url }}"
    product_id: '{C4443D4E-AC00-CF0E-9519-C9111E83ADBB}'
    arguments: /quiet /installpath c:\ADK /features OptionId.DeploymentTools OptionId.WindowsPreinstallationEnvironment

- name: copy files
  win_copy:
    src: "{{ item }}"
    dest: "{{ temp_directory }}\\{{ item }}"
  with_items:
    - winpeshl.ini
    - setsysname.cmd

- name: create files
  win_template:
    src: "{{ item }}"
    dest: "{{ temp_directory }}\\{{ item }}"
  with_items:
    - init.cmd

- name: download curl
  win_get_url:
    url: "{{ curl_download_url }}"
    dest: "{{ temp_directory }}\\curl.zip"

- name: unzip curl
  win_unzip:
    src: "{{ temp_directory }}\\curl.zip"
    dest: "{{ temp_directory }}"
    creates: "{{ temp_directory }}\\curl-7.61.0-win64-mingw"

- name: create a working copy of the windows pe files
  win_shell: '"..\\Deployment Tools\\DandISetEnv.bat" & copype amd64 C:\{{ winpe_name }}'
  args:
    executable: cmd
    chdir: C:\ADK\Assessment and Deployment Kit\Windows Preinstallation Environment
    creates: C:\{{ winpe_name }}

#- name: mount windows pe image
#  win_shell: Dism /Mount-Image /ImageFile:"C:\{{ winpe_name }}\media\sources\boot.wim" /Index:1 /MountDir:"C:\{{ winpe_name }}\mount"
#  args:
#    executable: cmd
#    chdir: C:\ADK\Assessment and Deployment Kit\Windows Preinstallation Environment
#    creates: C:\{{ winpe_name }}\mount\Windows
#
#- name: add packages
#  win_shell: Dism /Add-Package /Image:"C:\{{ winpe_name }}\mount" /PackagePath:"c:\ADK\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\WinPE_OCs\{{ item }}"
#  args:
#    executable: cmd
#    chdir: C:\ADK\Assessment and Deployment Kit\Windows Preinstallation Environment
#  with_items:
#    - WinPE-WMI.cab
#    - en-us\WinPE-WMI_en-us.cab
#    - WinPE-NetFX.cab
#    - en-us\WinPE-NetFX_en-us.cab
#    - WinPE-Scripting.cab
#    - en-us\WinPE-Scripting_en-us.cab
#    - WinPE-PowerShell.cab
#    - en-us\WinPE-PowerShell_en-us.cab
#    - WinPE-StorageWMI.cab
#    - en-us\WinPE-StorageWMI_en-us.cab
#    - WinPE-DismCmdlets.cab
#    - en-us\WinPE-DismCmdlets_en-us.cab
#
#- name: unmount windows pe image
#  win_shell: Dism /Unmount-Image /MountDir:C:\{{ winpe_name }}\mount /Commit
#  args:
#    executable: cmd
#    chdir: C:\ADK\Assessment and Deployment Kit\Windows Preinstallation Environment
#    removes: C:\{{ winpe_name }}\mount\Windows

- name: copy script file
  win_template:
    src: create_winpe.ps1
    dest: "{{ temp_directory }}\\create_winpe.ps1"

- name: load powershell modules into winpe
  win_shell: "{{ temp_directory }}\\create_winpe.ps1"

- name: create winpe iso file
  win_shell: '"..\\Deployment Tools\\DandISetEnv.bat" & MakeWinPEMedia /ISO C:\{{ winpe_name }} {{ temp_directory }}\{{ winpe_name }}.iso'
  args:
    executable: cmd
    chdir: C:\ADK\Assessment and Deployment Kit\Windows Preinstallation Environment

- name: copy iso file
  win_copy:
    src: "{{ temp_directory }}\\{{ winpe_name }}.iso"
    dest: "{{ smb_share }}\\{{ destination_file_location }}\\"
    remote_src: yes
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ smb_share_username }}"
    ansible_become_pass: "{{ smb_share_password }}"

- name: clean up files
  win_file:
    path: "{{ temp_directory }}\\{{ item }}"
    state: absent
  with_items:
    - C:\{{ winpe_name }}
    - winpeshl.ini
    - setsysname.cmd
    - create_winpe.ps1
    - curl.zip