- name: generate_winpe
  hosts: tag_role_wadk:&tag_app_winpe
  become_method: runas
  become: no
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore

  pre_tasks:
    - name: add pcsx module
      win_psmodule:
        name: Pscx
        state: present
        allow_clobber: yes

    - name: install 7-zip
      win_chocolatey:
        name: 7zip.install
        state: present

  roles:
    - winpe